export default {
  GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATIONS_REQUEST",
  GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  GET_NOTIFICATIONS_FAILED: "GET_NOTIFICATIONS_FAILED",

  MARK_AS_READ: "MARK_AS_READ", // 标记为已读
  MARK_ALL_AS_READ: "MARK_ALL_AS_READ"
};
